"""
Phase 0 diagnostic for REQ-1: audit the raw LinkedIn dataset before any AC is frozen.

Reads every CSV under data/raw/ and reports shape, columns, dtypes, and null rates,
then runs targeted checks against the assumptions REQ-1 and REQ-2 are written on.
Output is written to data/processed/schema_audit.md (committed — it is the
"important fields" evidence report section 5 asks for).

pandas only, no Spark, so this runs before the JDK 17 setup is done.

    python -m src.audit_schema
"""

from __future__ import annotations

import json
from pathlib import Path

import pandas as pd

RAW = Path("data/raw")
OUT = Path("data/processed/schema_audit.md")
SAMPLE_ROWS = 5_000
CHUNK = 100_000

# Assumptions the spec is written on. Each is confirmed or refuted by this audit.
SPEC_CHECKS = {
    "postings.csv": [
        ("normalized_salary", "AC-1.4 prefers this column over deriving from pay_period"),
        ("skills_desc", "AC-2.3 uses this as the primary skill-extraction source"),
        ("remote_allowed", "AC-1.5 derives work_setting from this flag"),
        ("formatted_work_type", "AC-1.6 / employment_type source (NOT work setting)"),
        ("formatted_experience_level", "AC-1.6 seniority fallback for min_years_exp"),
        ("description", "AC-2.4 section parsing, AC-1.7 education regex"),
        ("location", "AC-6.2 geocoding input"),
        ("pay_period", "AC-1.4 fallback derivation"),
    ],
    "job_skills.csv": [("skill_abr", "AC-1.1 tech scoping join key")],
}


def profile_csv(path: Path) -> dict:
    """Column/dtype profile from a sample, exact row and null counts from a chunked pass."""
    sample = pd.read_csv(path, nrows=SAMPLE_ROWS, low_memory=False)

    n_rows = 0
    nulls = pd.Series(0, index=sample.columns, dtype="int64")
    for chunk in pd.read_csv(path, chunksize=CHUNK, low_memory=False):
        n_rows += len(chunk)
        nulls = nulls.add(chunk.isna().sum(), fill_value=0)

    return {
        "path": str(path.relative_to(RAW)),
        "rows": n_rows,
        "cols": len(sample.columns),
        "columns": list(sample.columns),
        "dtypes": {c: str(t) for c, t in sample.dtypes.items()},
        "null_pct": {c: round(100 * nulls[c] / n_rows, 1) if n_rows else 0.0
                     for c in sample.columns},
        "samples": {c: [str(v)[:60] for v in sample[c].dropna().head(2)]
                    for c in sample.columns},
    }


def main() -> None:
    csvs = sorted(RAW.rglob("*.csv"))
    if not csvs:
        raise SystemExit(
            f"No CSVs under {RAW}/. Download the dataset first:\n"
            "  kaggle datasets download -d arshkon/linkedin-job-postings -p data/raw --unzip"
        )

    profiles = [profile_csv(p) for p in csvs]

    lines = [
        "# Raw dataset schema audit",
        "",
        "Generated by `python -m src.audit_schema`. Phase 0 of REQ-1 — run before freezing",
        "REQ-1/REQ-2 so the acceptance criteria describe the real schema, not an assumed one.",
        "",
        "## Files",
        "",
        "| File | Rows | Columns |",
        "|---|---:|---:|",
    ]
    for p in profiles:
        lines.append(f"| `{p['path']}` | {p['rows']:,} | {p['cols']} |")

    for p in profiles:
        lines += ["", f"## `{p['path']}`", "",
                  "| Column | Dtype | Null % | Example |", "|---|---|---:|---|"]
        for c in p["columns"]:
            ex = p["samples"][c][0] if p["samples"][c] else "—"
            ex = ex.replace("|", "\\|")
            lines.append(f"| `{c}` | {p['dtypes'][c]} | {p['null_pct'][c]} | {ex} |")

    lines += ["", "## Spec assumption checks", "",
              "| File | Column | Present | Null % | Used by |", "|---|---|---|---:|---|"]
    by_name = {Path(p["path"]).name: p for p in profiles}
    for fname, checks in SPEC_CHECKS.items():
        prof = by_name.get(fname)
        for col, used_by in checks:
            if prof is None:
                lines.append(f"| `{fname}` | `{col}` | **FILE MISSING** | — | {used_by} |")
            elif col in prof["columns"]:
                lines.append(f"| `{fname}` | `{col}` | yes | {prof['null_pct'][col]} | {used_by} |")
            else:
                lines.append(f"| `{fname}` | `{col}` | **NO — spec needs amending** | — | {used_by} |")

    # skill_abr values drive AC-1.1's TECH_CODES constant.
    js = by_name.get("job_skills.csv")
    if js is not None:
        vals = pd.read_csv(RAW / js["path"], usecols=["skill_abr"])["skill_abr"]
        counts = vals.value_counts()
        lines += ["", "## `skill_abr` values (input to AC-1.1 `TECH_CODES`)", "",
                  "Confirms D4: these are coarse job-function codes, not tool-level skills.", "",
                  "| Code | Postings |", "|---|---:|"]
        lines += [f"| `{k}` | {v:,} |" for k, v in counts.items()]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")

    summary = {p["path"]: {"rows": p["rows"], "cols": p["cols"]} for p in profiles}
    print(json.dumps(summary, indent=2))
    print(f"\nWrote {OUT}")


if __name__ == "__main__":
    main()
